-- MySQL Script generated by MySQL Workbench
-- Mon May 23 08:00:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering



SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Melina_Sandoval
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Melina_Sandoval
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Melina_Sandoval` DEFAULT CHARACTER SET utf8mb4 ;
USE `Melina_Sandoval` ;

-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Adresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Adresses` (
  `id` INT NOT NULL,
  `street_number` INT NOT NULL,
  `street_nama` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Computer_Problem_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Computer_Problem_Types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `problem_type` VARCHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Computer_Problems_Sub_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Computer_Problems_Sub_Types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sub_type_problem_description` VARCHAR(255) NULL DEFAULT NULL,
  `sub_price` DOUBLE NULL DEFAULT NULL,
  `computer_problem_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Computer_Problems_Sub_Types_Computer_Problem_Types1_idx` (`computer_problem_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Computer_Problems_Sub_Types_Computer_Problem_Types1`
    FOREIGN KEY (`computer_problem_type_id`)
    REFERENCES `Melina_Sandoval`.`Computer_Problem_Types` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Data_Storage_Devices_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Data_Storage_Devices_Types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_storage_type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Operating_Systems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Operating_Systems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `o_s` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Processors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Processors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Computers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Computers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(255) NOT NULL,
  `year` INT NOT NULL,
  `operating_system_id` INT NOT NULL,
  `processor_id` INT NOT NULL,
  `data_storage_device_type_id` INT NOT NULL,
  `data_storage_device_capacity` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Computers_Operating_Systems1_idx` (`operating_system_id` ASC) VISIBLE,
  INDEX `fk_Computers_Processors1_idx` (`processor_id` ASC) VISIBLE,
  INDEX `fk_Computers_Data_Storage_Devices_Types1_idx` (`data_storage_device_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Computers_Data_Storage_Devices_Types1`
    FOREIGN KEY (`data_storage_device_type_id`)
    REFERENCES `Melina_Sandoval`.`Data_Storage_Devices_Types` (`id`),
  CONSTRAINT `fk_Computers_Operating_Systems1`
    FOREIGN KEY (`operating_system_id`)
    REFERENCES `Melina_Sandoval`.`Operating_Systems` (`id`),
  CONSTRAINT `fk_Computers_Processors1`
    FOREIGN KEY (`processor_id`)
    REFERENCES `Melina_Sandoval`.`Processors` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Genders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Genders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Phone_Numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Phone_Numbers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_code` INT NOT NULL,
  `phone_number` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `user_phone_number_id` INT NOT NULL,
  `adress_id` INT NOT NULL,
  `genders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_User_Phone_Numbers_idx` (`user_phone_number_id` ASC) VISIBLE,
  INDEX `fk_Users_Adresses1_idx` (`adress_id` ASC) VISIBLE,
  INDEX `fk_Users_Genders1_idx` (`genders_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Adresses1`
    FOREIGN KEY (`adress_id`)
    REFERENCES `Melina_Sandoval`.`Adresses` (`id`),
  CONSTRAINT `fk_Users_Genders1`
    FOREIGN KEY (`genders_id`)
    REFERENCES `Melina_Sandoval`.`Genders` (`id`),
  CONSTRAINT `fk_Users_User_Phone_Numbers`
    FOREIGN KEY (`user_phone_number_id`)
    REFERENCES `Melina_Sandoval`.`Phone_Numbers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Employee_IDs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Employee_IDs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_IDs` VARCHAR(45) NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Employee_IDs_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_IDs_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `Melina_Sandoval`.`Users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Computers_For_Rapair`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Computers_For_Rapair` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `computer_id` INT NOT NULL,
  `costumer_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `entry_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Computers_For_Rapair_ComputerS1_idx` (`computer_id` ASC) VISIBLE,
  INDEX `fk_Computers_For_Rapair_Users1_idx` (`costumer_id` ASC) VISIBLE,
  INDEX `fk_Computers_For_Rapair_Employee_IDs1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Computers_For_Rapair_ComputerS1`
    FOREIGN KEY (`computer_id`)
    REFERENCES `Melina_Sandoval`.`Computers` (`id`),
  CONSTRAINT `fk_Computers_For_Rapair_Users1`
    FOREIGN KEY (`costumer_id`)
    REFERENCES `Melina_Sandoval`.`Users` (`id`),
  CONSTRAINT `fk_Computers_For_Rapair_Employee_IDs1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Melina_Sandoval`.`Employee_IDs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Computers_For_Rapair_Diagnosis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Computers_For_Rapair_Diagnosis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `computer_for_rapair_id` INT NOT NULL,
  `computer_problem_sub_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Computers_For_Rapair_has_Computer_Problems_Sub_Types_Com_idx` (`computer_problem_sub_type_id` ASC) VISIBLE,
  INDEX `fk_Computers_For_Rapair_has_Computer_Problems_Sub_Types_Com_idx1` (`computer_for_rapair_id` ASC) VISIBLE,
  CONSTRAINT `fk_Computers_For_Rapair_has_Computer_Problems_Sub_Types_Compu1`
    FOREIGN KEY (`computer_for_rapair_id`)
    REFERENCES `Melina_Sandoval`.`Computers_For_Rapair` (`id`),
  CONSTRAINT `fk_Computers_For_Rapair_has_Computer_Problems_Sub_Types_Compu2`
    FOREIGN KEY (`computer_problem_sub_type_id`)
    REFERENCES `Melina_Sandoval`.`Computer_Problems_Sub_Types` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Work_Schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Work_Schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `work_Day` VARCHAR(45) NOT NULL,
  `shift` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Melina_Sandoval`.`Employee_Work_Schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Melina_Sandoval`.`Employee_Work_Schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `work_schedules_id` INT NOT NULL,
  INDEX `fk_Work_Schedules_has_Employee_IDs_Employee_IDs1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_Work_Schedules_has_Employee_IDs_Work_Schedules1_idx` (`work_schedules_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Work_Schedules_has_Employee_IDs_Work_Schedules1`
    FOREIGN KEY (`work_schedules_id`)
    REFERENCES `Melina_Sandoval`.`Work_Schedules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Work_Schedules_has_Employee_IDs_Employee_IDs1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Melina_Sandoval`.`Employee_IDs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
